# @package _global_
defaults:
  - _self_

openai_api_key:
model_name: DeepSeek-R1-Distill-Qwen-1.5B
max_context_length: 4096 #4096
exllama: False
#Set the temperature within the range of 0.5-0.7 (0.6 is recommended) to prevent endless repetitions or incoherent outputs.
temperature: 0.6

system_tag_start: "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n"
system_tag_end: "<|eot_id|>"

user_tag_start: "<|start_header_id|>user<|end_header_id|>\n\n"
user_tag_end: "<|eot_id|>"

ai_tag_start: "<|start_header_id|>assistant<|end_header_id|>\n\n"
ai_tag_end: "<|eot_id|>"

stop_words:
 - "<|eot_id|>"