# @package _global_
defaults:
  - _self_

# MaziyarPanahi/Meta-Llama-3-8B-Instruct-GPTQ
openai_api_key:
# model_name: Llama-3.1-8B-Instruct-EXL2-2.0bpw
model_name: Llama-3.2-1B-Instruct-exl2-4.0bpw
# model_name: Meta-Llama-3-8B-Instruct-GPTQ
max_context_length: 4096
exllama: True

system_tag_start: "<s>[INST] <<SYS>>\n"
system_tag_end: "\n<</SYS>>\n\n"

user_tag_start: ""
user_tag_end: " [/INST] "

ai_tag_start: ""
ai_tag_end: " </s><s>[INST] "

stop_words:
 - "[INST]"
 - "[/INST]"