# @package _global_
defaults:
  - _self_

# MaziyarPanahi/Meta-Llama-3-8B-Instruct-GPTQ
openai_api_key:
# model_name: Llama-3.1-8B-Instruct-EXL2-2.0bpw
model_name: Llama-3.2-1B-Instruct-exl2-4.0bpw
# model_name: Meta-Llama-3-8B-Instruct-GPTQ
max_context_length: 4096
exllama: True

system_tag_start: "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n"
system_tag_end: "<|eot_id|>"

user_tag_start: "<|start_header_id|>user<|end_header_id|>\n\n"
user_tag_end: "<|eot_id|>"

ai_tag_start: "<|start_header_id|>assistant<|end_header_id|>\n\n"
ai_tag_end: "<|eot_id|>"

stop_words:
 - "<|eot_id|>"