# @package _global_
defaults:
  - _self_

rag_name: MedCPT_md_k10
rag_embedding_model: MedCPT-Cross-Encoder

#Embedding model parameters
rag_chunk_size: 252
rag_chunk_overlap: 0

rag_smart_chunking: True #For markdown

#Retrieval parameters
rag_top_k: 10
rag_re_rank: False
rag_prompt_name: "s2p_query" # or "s2s_query" depending on your task #TODO: C'est quoi ca

# Document paths for retrieval
rag_documents:
  - /markdown/cdm_appendicitis_s13017-020-00306-3_edited.md
  - /markdown/cdm_cholecystitis_s13017-020-00336-x.md
  - /markdown/cdm_diverticulitis_the_american_society_of_colon_and_rectal_surgeons.6.md
  - /markdown/cdm_pancreatitis_s13017-019-0247-0.md

# RAG Leaderboard: https://huggingface.co/spaces/mteb/leaderboard