# @package _global_
defaults:
  - _self_

rag_name: all-MiniLM-L6-v2
rag_embedding_model: all-MiniLM-L6-v2
#Embedding model parameters
rag_chunk_size: 384
rag_chunk_overlap: 76

rag_smart_chunking: True #For markdown

rag_embed_max_length: 512

#Retrieval parameters
rag_top_k: 8
rag_re_rank: True
rag_top_k_rerank: 3
rag_prompt_name: "None"

# Document paths for retrieval
rag_documents:
  - /markdown/cdm_appendicitis_s13017-020-00306-3_edited.md
  - /markdown/cdm_cholecystitis_s13017-020-00336-x.md
  - /markdown/cdm_diverticulitis_the_american_society_of_colon_and_rectal_surgeons.6.md
  - /markdown/cdm_pancreatitis_s13017-019-0247-0.md

# RAG Leaderboard: https://huggingface.co/spaces/mteb/leaderboard