# @package _global_
defaults:
  - _self_

rag_name: NV-Embed-v2
rag_embedding_model: NV-Embed-v2

#Embedding model parameters
rag_chunk_size: 252
rag_chunk_overlap: 0

rag_smart_chunking: True #For markdown

#Retrieval parameters
rag_top_k: 4
rag_re_rank: True
rag_prompt_name: "s2p_query" # or "s2s_query" depending on your task #TODO: C'est quoi ca

# Document paths for retrieval
rag_documents:
  - /pdf/cdm_appendicitis_s13017-020-00306-3.pdf
  - /pdf/cdm_cholecystitis_s13017-020-00336-x.pdf
  - /pdf/cdm_diverticulitis_the_american_society_of_colon_and_rectal_surgeons.6.pdf
  - /pdf/cdm_pancreatitis_s13017-019-0247-0.pdf
  # - /chunkr/cdm_appendicitis_s13017-020-00306-3.json
  # - /chunkr/cdm_cholecystitis_s13017-020-00336-x.json
  # - /chunkr/cdm_diverticulitis_the_american_society_of_colon_and_rectal_surgeons.6.json
  # - /chunkr/cdm_pancreatitis_s13017-019-0247-0.json

# RAG Leaderboard: https://huggingface.co/spaces/mteb/leaderboard