# @package _global_
defaults:
  - _self_

rag_name: stella_en_400M_v5
rag_embedding_model: stella_en_400M_v5

#Embedding model parameters
rag_chunk_size: 252
rag_chunk_overlap: 0

rag_smart_chunking: True #For markdown

#Retrieval parameters
rag_top_k: 4
rag_re_rank: True
rag_prompt_name: "s2p_query" # or "s2s_query" s2p = (short query to long passage)

# Document paths for retrieval
rag_documents:
  - /pdf/cdm_appendicitis_s13017-020-00306-3.pdf
  - /pdf/cdm_cholecystitis_s13017-020-00336-x.pdf
  - /pdf/cdm_diverticulitis_the_american_society_of_colon_and_rectal_surgeons.6.pdf
  - /pdf/cdm_pancreatitis_s13017-019-0247-0.pdf
  # - /chunkr/cdm_appendicitis_s13017-020-00306-3.json
  # - /chunkr/cdm_cholecystitis_s13017-020-00336-x.json
  # - /chunkr/cdm_diverticulitis_the_american_society_of_colon_and_rectal_surgeons.6.json
  # - /chunkr/cdm_pancreatitis_s13017-019-0247-0.json
  # - /markdown/cdm_appendicitis_s13017-020-00306-3_edited.md
  # - /markdown/cdm_cholecystitis_s13017-020-00336-x.md
  # - /markdown/cdm_diverticulitis_the_american_society_of_colon_and_rectal_surgeons.6.md
  # - /markdown/cdm_pancreatitis_s13017-019-0247-0.md

# RAG Leaderboard: https://huggingface.co/spaces/mteb/leaderboard